// apps/airbnb-react-app/src/components/search-filters.tsx
import { useState } from "react";
import {
  type CatalogFilters,
  type CatalogOptions,
  createDefaultFilters,
  SORT_OPTIONS,
} from "../catalog";

interface SearchFiltersProps {
  disabled: boolean;
  initialFilters: CatalogFilters;
  onReset: () => void;
  onSearch: (filters: CatalogFilters) => void;
  options: CatalogOptions;
}

const NUMBER_FILTERS = [
  ["minPrice", "Harga minimum", "Mulai dari...", 0],
  ["maxPrice", "Harga maksimum", "Hingga...", 0],
  ["guests", "Tamu minimum", "Jumlah tamu...", 1],
  ["bedrooms", "Kamar tidur", "Jumlah kamar...", 1],
  ["beds", "Tempat tidur", "Jumlah tempat tidur...", 1],
  ["bathrooms", "Kamar mandi", "Jumlah kamar...", 1],
] as const;

function copyFilters(filters: CatalogFilters): CatalogFilters {
  return { ...filters, amenities: [...filters.amenities] };
}

export default function SearchFilters({
  disabled,
  initialFilters,
  onReset,
  onSearch,
  options,
}: SearchFiltersProps) {
  const [draft, setDraft] = useState(() => copyFilters(initialFilters));

  function updateField(name: keyof CatalogFilters, value: string) {
    setDraft((current) => ({ ...current, [name]: value }));
  }

  function toggleAmenity(id: string) {
    setDraft((current) => ({
      ...current,
      amenities: current.amenities.includes(id)
        ? current.amenities.filter((amenity) => amenity !== id)
        : [...current.amenities, id],
    }));
  }

  function reset() {
    setDraft(createDefaultFilters());
    onReset();
  }

  return (
    <form
      aria-busy={disabled}
      className="search-panel"
      onSubmit={(event) => {
        event.preventDefault();
        onSearch(copyFilters(draft));
      }}
    >
      <div className="search-panel__primary">
        <label className="field field--search">
          <span className="field__label">Cari</span>
          <input
            autoComplete="off"
            disabled={disabled}
            name="search"
            onChange={(event) => updateField("search", event.target.value)}
            placeholder="Contoh: vila di Bali..."
            type="search"
            value={draft.search}
          />
        </label>

        <label className="field">
          <span className="field__label">Lokasi</span>
          <select
            disabled={disabled}
            name="location"
            onChange={(event) => updateField("location", event.target.value)}
            value={draft.location}
          >
            <option value="">Semua lokasi</option>
            {options.locations.map((location) => (
              <option key={location.id} value={location.id}>
                {location.displayName}
              </option>
            ))}
          </select>
        </label>

        <label className="field">
          <span className="field__label">Tipe</span>
          <select
            disabled={disabled}
            name="type"
            onChange={(event) => updateField("type", event.target.value)}
            value={draft.type}
          >
            <option value="">Semua tipe</option>
            {options.propertyTypes.map((propertyType) => (
              <option key={propertyType.id} value={propertyType.slug}>
                {propertyType.name}
              </option>
            ))}
          </select>
        </label>

        <button className="search-button" disabled={disabled} type="submit">
          {disabled ? "Mencari..." : "Cari properti"}
        </button>
      </div>

      <div className="search-panel__secondary">
        <label className="field">
          <span className="field__label">Urutkan</span>
          <select
            disabled={disabled}
            name="sort"
            onChange={(event) => updateField("sort", event.target.value)}
            value={draft.sort}
          >
            {SORT_OPTIONS.map((option) => (
              <option key={option.value} value={option.value}>
                {option.label}
              </option>
            ))}
          </select>
        </label>

        <details className="advanced-filters">
          <summary>
            <span className="advanced-filters__summary-copy">
              <strong>Filter lanjutan</strong>
              <span>Harga, kapasitas, dan amenitas</span>
            </span>
            <span aria-hidden="true" className="advanced-filters__indicator">
              +
            </span>
          </summary>
          <div className="advanced-filters__body">
            <div className="advanced-filters__grid">
              {NUMBER_FILTERS.map(([name, label, placeholder, min]) => (
                <label className="field" key={name}>
                  <span className="field__label">{label}</span>
                  <input
                    autoComplete="off"
                    disabled={disabled}
                    inputMode="numeric"
                    min={min}
                    name={name}
                    onChange={(event) => updateField(name, event.target.value)}
                    placeholder={placeholder}
                    type="number"
                    value={draft[name]}
                  />
                </label>
              ))}
            </div>

            <fieldset className="amenities">
              <legend>Amenitas wajib</legend>
              {options.amenities.map((amenity) => (
                <label className="amenity-option" key={amenity.id}>
                  <input
                    checked={draft.amenities.includes(amenity.id)}
                    disabled={disabled}
                    name="amenities"
                    onChange={() => toggleAmenity(amenity.id)}
                    type="checkbox"
                    value={amenity.id}
                  />
                  <span>{amenity.name}</span>
                </label>
              ))}
            </fieldset>
          </div>
        </details>

        <button
          className="reset-button"
          disabled={disabled}
          onClick={reset}
          type="button"
        >
          Reset filter
        </button>
      </div>
    </form>
  );
}

// apps/airbnb-svelte-app/src/components/SearchFilters.svelte
<script lang="ts">
  import { untrack } from "svelte";
  import {
    type CatalogFilters,
    type CatalogOptions,
    createDefaultFilters,
    SORT_OPTIONS,
  } from "../catalog";

  interface Props {
    disabled: boolean;
    initialFilters: CatalogFilters;
    options: CatalogOptions;
    reset: () => void;
    search: (filters: CatalogFilters) => void;
  }

  let { disabled, initialFilters, options, reset, search }: Props = $props();
  const numericFilterKeys = [
    "minPrice",
    "maxPrice",
    "guests",
    "bedrooms",
    "beds",
    "bathrooms",
  ] as const;
  let draft: CatalogFilters = $state(
    untrack(() => copyFilters(initialFilters))
  );

  function copyFilters(filters: CatalogFilters): CatalogFilters {
    const copy = {
      ...filters,
      amenities: [...filters.amenities],
    };

    for (const key of numericFilterKeys) {
      copy[key] = String(copy[key] ?? "").trim();
    }

    return copy;
  }

  function copyDraft(): CatalogFilters {
    return copyFilters(draft);
  }

  function submit(event: SubmitEvent): void {
    event.preventDefault();
    search(copyDraft());
  }

  function resetFilters(): void {
    draft = createDefaultFilters();
    reset();
  }
</script>

<form class="search-panel" aria-busy={disabled} onsubmit={submit}>
  <div class="search-panel__primary">
    <label class="field field--search">
      <span class="field__label">Cari</span>
      <input
        bind:value={draft.search}
        autocomplete="off"
        {disabled}
        name="search"
        placeholder="Contoh: vila di Bali&#8230;"
        type="search"
      >
    </label>

    <label class="field">
      <span class="field__label">Lokasi</span>
      <select bind:value={draft.location} {disabled} name="location">
        <option value="">Semua lokasi</option>
        {#each options.locations as location (location.id)}
          <option value={location.id}>{location.displayName}</option>
        {/each}
      </select>
    </label>

    <label class="field">
      <span class="field__label">Tipe</span>
      <select bind:value={draft.type} {disabled} name="type">
        <option value="">Semua tipe</option>
        {#each options.propertyTypes as propertyType (propertyType.id)}
          <option value={propertyType.slug}>{propertyType.name}</option>
        {/each}
      </select>
    </label>

    <button class="search-button" {disabled} type="submit">
      {disabled ? "Mencari\u2026" : "Cari properti"}
    </button>
  </div>

  <div class="search-panel__secondary">
    <label class="field">
      <span class="field__label">Urutkan</span>
      <select bind:value={draft.sort} {disabled} name="sort">
        {#each SORT_OPTIONS as option (option.value)}
          <option value={option.value}>{option.label}</option>
        {/each}
      </select>
    </label>

    <details class="advanced-filters">
      <summary>
        <span class="advanced-filters__summary-copy">
          <strong>Filter lanjutan</strong>
          <span>Harga, kapasitas, dan amenitas</span>
        </span>
        <span class="advanced-filters__indicator" aria-hidden="true">+</span>
      </summary>
      <div class="advanced-filters__body">
        <div class="advanced-filters__grid">
          <label class="field">
            <span class="field__label">Harga minimum</span>
            <input
              bind:value={draft.minPrice}
              autocomplete="off"
              {disabled}
              inputmode="numeric"
              min="0"
              name="minPrice"
              placeholder="Mulai dari&#8230;"
              type="number"
            >
          </label>
          <label class="field">
            <span class="field__label">Harga maksimum</span>
            <input
              bind:value={draft.maxPrice}
              autocomplete="off"
              {disabled}
              inputmode="numeric"
              min="0"
              name="maxPrice"
              placeholder="Hingga&#8230;"
              type="number"
            >
          </label>
          <label class="field">
            <span class="field__label">Tamu minimum</span>
            <input
              bind:value={draft.guests}
              autocomplete="off"
              {disabled}
              inputmode="numeric"
              min="1"
              name="guests"
              placeholder="Jumlah tamu&#8230;"
              type="number"
            >
          </label>
          <label class="field">
            <span class="field__label">Kamar tidur</span>
            <input
              bind:value={draft.bedrooms}
              autocomplete="off"
              {disabled}
              inputmode="numeric"
              min="1"
              name="bedrooms"
              placeholder="Jumlah kamar&#8230;"
              type="number"
            >
          </label>
          <label class="field">
            <span class="field__label">Tempat tidur</span>
            <input
              bind:value={draft.beds}
              autocomplete="off"
              {disabled}
              inputmode="numeric"
              min="1"
              name="beds"
              placeholder="Jumlah tempat tidur&#8230;"
              type="number"
            >
          </label>
          <label class="field">
            <span class="field__label">Kamar mandi</span>
            <input
              bind:value={draft.bathrooms}
              autocomplete="off"
              {disabled}
              inputmode="numeric"
              min="1"
              name="bathrooms"
              placeholder="Jumlah kamar mandi&#8230;"
              type="number"
            >
          </label>
        </div>

        <fieldset class="amenities">
          <legend>Amenitas wajib</legend>
          {#each options.amenities as amenity (amenity.id)}
            <label class="amenity-option">
              <input
                bind:group={draft.amenities}
                {disabled}
                name="amenities"
                type="checkbox"
                value={amenity.id}
              >
              <span>{amenity.name}</span>
            </label>
          {/each}
        </fieldset>
      </div>
    </details>

    <button
      class="reset-button"
      {disabled}
      type="button"
      onclick={resetFilters}
    >
      Reset filter
    </button>
  </div>
</form>
