// apps/airbnb-react-app/src/components/property-explorer.tsx
import type {
  PaginatedResponse,
  PropertyDetail as PropertyDetailType,
  PropertyListItem,
} from "@airbnb-skripsi/api/catalog";
import {
  type ReactNode,
  useCallback,
  useEffect,
  useRef,
  useState,
} from "react";
import {
  type CatalogFilters,
  type CatalogOptions,
  createCatalogSearchParams,
  createDefaultFilters,
  createPropertyPath,
  fetchCatalogOptions,
  fetchPropertyDetail,
  fetchPropertyPage,
  parseCatalogFilters,
  parsePropertySlug,
} from "../catalog";
import PropertyDetail from "./property-detail";
import PropertyGrid from "./property-grid";
import SearchFilters from "./search-filters";

type PaginationMeta = PaginatedResponse<PropertyListItem>["meta"];
const EMPTY_OPTIONS: CatalogOptions = {
  amenities: [],
  locations: [],
  propertyTypes: [],
};
const SKELETON_ITEMS = [0, 1, 2, 3];

function messageFrom(error: unknown): string {
  return error instanceof Error
    ? error.message
    : "Terjadi kesalahan. Coba lagi.";
}

export default function PropertyExplorer() {
  const [options, setOptions] = useState<CatalogOptions>(EMPTY_OPTIONS);
  const [filters, setFilters] = useState<CatalogFilters>(createDefaultFilters);
  const [filterFormKey, setFilterFormKey] = useState(0);
  const [properties, setProperties] = useState<PropertyListItem[]>([]);
  const [pagination, setPagination] = useState<PaginationMeta | null>(null);
  const [detail, setDetail] = useState<PropertyDetailType | null>(null);
  const [selectedSlug, setSelectedSlug] = useState<string | null>(null);
  const [wishlistStates, setWishlistStates] = useState<Map<string, boolean>>(
    () => new Map()
  );
  const [loadingOptions, setLoadingOptions] = useState(false);
  const [loadingList, setLoadingList] = useState(false);
  const [loadingDetail, setLoadingDetail] = useState(false);
  const [optionsError, setOptionsError] = useState<string | null>(null);
  const [listError, setListError] = useState<string | null>(null);
  const [detailError, setDetailError] = useState<string | null>(null);
  const listRequestId = useRef(0);
  const detailRequestId = useRef(0);
  const optionsLoaded = useRef(false);

  const mergeWishlist = useCallback(
    (items: Array<PropertyListItem | PropertyDetailType>) => {
      setWishlistStates((current) => {
        const next = new Map(current);
        for (const item of items) {
          if (!next.has(item.id)) {
            next.set(item.id, item.isWishlisted);
          }
        }
        return next;
      });
    },
    []
  );

  const loadOptions = useCallback(async () => {
    if (optionsLoaded.current) {
      return;
    }
    optionsLoaded.current = true;
    setLoadingOptions(true);
    setOptionsError(null);
    try {
      setOptions(await fetchCatalogOptions());
    } catch (error) {
      optionsLoaded.current = false;
      setOptionsError(messageFrom(error));
    } finally {
      setLoadingOptions(false);
    }
  }, []);

  const loadPropertyList = useCallback(
    async (activeFilters: CatalogFilters, page: number, append: boolean) => {
      const requestId = ++listRequestId.current;
      setLoadingList(true);
      setListError(null);
      try {
        const response = await fetchPropertyPage(activeFilters, page);
        if (requestId !== listRequestId.current) {
          return;
        }
        setProperties((current) =>
          append ? [...current, ...response.data] : response.data
        );
        setPagination(response.meta);
        mergeWishlist(response.data);
      } catch (error) {
        if (requestId === listRequestId.current) {
          setListError(messageFrom(error));
        }
      } finally {
        if (requestId === listRequestId.current) {
          setLoadingList(false);
        }
      }
    },
    [mergeWishlist]
  );

  const openProperty = useCallback(
    async (slug: string, updateUrl = true) => {
      const requestId = ++detailRequestId.current;
      setSelectedSlug(slug);
      setDetail(null);
      setDetailError(null);
      setLoadingDetail(true);

      if (updateUrl) {
        const catalogUrl = `${window.location.pathname}${window.location.search}${window.location.hash}`;
        window.history.pushState({ catalogUrl }, "", createPropertyPath(slug));
      }
      window.scrollTo({ behavior: "smooth", top: 0 });

      try {
        const response = await fetchPropertyDetail(slug);
        if (requestId !== detailRequestId.current) {
          return;
        }
        setDetail(response);
        mergeWishlist([response]);
      } catch (error) {
        if (requestId === detailRequestId.current) {
          setDetailError(messageFrom(error));
        }
      } finally {
        if (requestId === detailRequestId.current) {
          setLoadingDetail(false);
        }
      }
    },
    [mergeWishlist]
  );

  const clearDetail = useCallback(() => {
    detailRequestId.current += 1;
    setSelectedSlug(null);
    setDetail(null);
    setDetailError(null);
    setLoadingDetail(false);
  }, []);

  const loadCatalog = useCallback(() => {
    const nextFilters = parseCatalogFilters(
      new URLSearchParams(window.location.search)
    );
    setFilters(nextFilters);
    setFilterFormKey((key) => key + 1);
    clearDetail();
    Promise.all([loadOptions(), loadPropertyList(nextFilters, 1, false)]).catch(
      () => undefined
    );
  }, [clearDetail, loadOptions, loadPropertyList]);

  const syncRoute = useCallback(() => {
    const slug = parsePropertySlug(window.location.pathname);
    if (slug) {
      openProperty(slug, false).catch(() => undefined);
    } else {
      loadCatalog();
    }
  }, [loadCatalog, openProperty]);

  useEffect(() => {
    syncRoute();
    window.addEventListener("popstate", syncRoute);
    return () => window.removeEventListener("popstate", syncRoute);
  }, [syncRoute]);

  function updateCatalogUrl(nextFilters: CatalogFilters) {
    const url = new URL(window.location.href);
    url.search = createCatalogSearchParams(
      nextFilters,
      url.searchParams
    ).toString();
    const nextUrl = `${url.pathname}${url.search}${url.hash}`;
    const currentUrl = `${window.location.pathname}${window.location.search}${window.location.hash}`;
    if (nextUrl !== currentUrl) {
      window.history.pushState(null, "", nextUrl);
    }
  }

  function handleSearch(nextFilters: CatalogFilters) {
    setFilters(nextFilters);
    updateCatalogUrl(nextFilters);
    clearDetail();
    loadPropertyList(nextFilters, 1, false).catch(() => undefined);
  }

  function closeDetail() {
    if (typeof window.history.state?.catalogUrl === "string") {
      window.history.back();
      return;
    }
    window.history.pushState(null, "", "/");
    loadCatalog();
    window.scrollTo({ behavior: "smooth", top: 0 });
  }

  function toggleWishlist(id: string) {
    setWishlistStates((current) => {
      const next = new Map(current);
      next.set(id, !(next.get(id) ?? false));
      return next;
    });
  }

  return (
    <div className="app">
      <a className="skip-link" href="#main-content">
        Langsung ke konten utama
      </a>
      <header className="site-header">
        <a aria-label="Airbnb beranda" className="brand" href="/">
          <span aria-hidden="true" className="brand__mark">
            A
          </span>
          <span translate="no">Airbnb</span>
        </a>
        <p>
          Prototipe listing
          <span aria-hidden="true" className="site-header__separator">
            /
          </span>
          Studi kasus Airbnb
        </p>
      </header>

      <main className="container" id="main-content">
        {selectedSlug ? (
          <DetailState
            detail={detail}
            error={detailError}
            loading={loadingDetail}
            onBack={closeDetail}
            onToggleWishlist={toggleWishlist}
            wishlisted={
              detail ? (wishlistStates.get(detail.id) ?? false) : false
            }
          />
        ) : (
          <>
            <section aria-labelledby="hero-title" className="hero">
              <div className="hero__intro">
                <div className="hero__copy-block">
                  <p className="hero__eyebrow">Eksperimen frontend skripsi</p>
                  <h1 id="hero-title">
                    Temukan tempat singgah.
                    <span className="hero__accent">Bandingkan tanpa bias.</span>
                  </h1>
                  <p className="hero__copy">
                    Jelajahi prototipe listing akomodasi dengan pencarian,
                    filter, dan detail yang setara pada implementasi Vue dan
                    Svelte.
                  </p>
                </div>

                <aside
                  aria-label="Konteks penelitian"
                  className="research-rail"
                >
                  <div>
                    <span>Dataset</span>
                    <strong>Dummy deterministik</strong>
                  </div>
                  <div>
                    <span>API</span>
                    <strong>Respons yang sama</strong>
                  </div>
                  <div>
                    <span>Frontend</span>
                    <strong>Vue + Svelte</strong>
                  </div>
                </aside>
              </div>

              <SearchFilters
                disabled={loadingList || loadingOptions}
                initialFilters={filters}
                key={filterFormKey}
                onReset={() => handleSearch(createDefaultFilters())}
                onSearch={handleSearch}
                options={options}
              />
            </section>

            <ResultsState
              error={listError ?? optionsError}
              filters={filters}
              loading={loadingList}
              loadPropertyList={loadPropertyList}
              onOpen={openProperty}
              onReset={() => handleSearch(createDefaultFilters())}
              onToggleWishlist={toggleWishlist}
              pagination={pagination}
              properties={properties}
              wishlistStates={wishlistStates}
            />
          </>
        )}
      </main>

      <footer className="site-footer">
        <p>
          <strong>Prototipe akademik</strong>
        </p>
        <p>
          Data dummy deterministik <span aria-hidden="true">{"\u00b7"}</span>{" "}
          Tanpa pemesanan atau transaksi
        </p>
      </footer>
    </div>
  );
}

interface DetailStateProps {
  detail: PropertyDetailType | null;
  error: string | null;
  loading: boolean;
  onBack: () => void;
  onToggleWishlist: (id: string) => void;
  wishlisted: boolean;
}

interface ResultsStateProps {
  error: string | null;
  filters: CatalogFilters;
  loading: boolean;
  loadPropertyList: (
    filters: CatalogFilters,
    page: number,
    append: boolean
  ) => Promise<void>;
  onOpen: (slug: string) => Promise<void>;
  onReset: () => void;
  onToggleWishlist: (id: string) => void;
  pagination: PaginationMeta | null;
  properties: PropertyListItem[];
  wishlistStates: ReadonlyMap<string, boolean>;
}

function ResultsState({
  error,
  filters,
  loading,
  loadPropertyList,
  onOpen,
  onReset,
  onToggleWishlist,
  pagination,
  properties,
  wishlistStates,
}: ResultsStateProps) {
  let content: ReactNode;

  if (error) {
    content = (
      <div className="status-panel status-panel--error" role="alert">
        <p>{error}</p>
        <button
          onClick={() => {
            loadPropertyList(filters, 1, false).catch(() => undefined);
          }}
          type="button"
        >
          Coba lagi
        </button>
      </div>
    );
  } else if (loading && properties.length === 0) {
    content = (
      <div aria-live="polite" className="skeleton-grid" role="status">
        <span className="sr-only">Memuat properti...</span>
        {SKELETON_ITEMS.map((item) => (
          <div className="skeleton-card" key={item} />
        ))}
      </div>
    );
  } else if (properties.length === 0) {
    content = (
      <div aria-live="polite" className="status-panel">
        <p>Tidak ada properti yang cocok dengan filter ini.</p>
        <button onClick={onReset} type="button">
          Reset filter
        </button>
      </div>
    );
  } else {
    content = (
      <>
        <PropertyGrid
          onOpen={(slug) => {
            onOpen(slug).catch(() => undefined);
          }}
          onToggleWishlist={onToggleWishlist}
          properties={properties}
          wishlistStates={wishlistStates}
        />
        <div className="load-more">
          {pagination?.hasMore ? (
            <button
              disabled={loading}
              onClick={() => {
                loadPropertyList(filters, pagination.page + 1, true).catch(
                  () => undefined
                );
              }}
              type="button"
            >
              {loading ? "Memuat..." : "Muat lebih banyak"}
            </button>
          ) : (
            <p>Semua properti sudah ditampilkan.</p>
          )}
        </div>
      </>
    );
  }

  return (
    <section aria-labelledby="results-title" className="results">
      <div className="results__heading">
        <div>
          <p className="results__eyebrow">Katalog akomodasi</p>
          <h2 aria-live="polite" id="results-title">
            {pagination?.total ?? 0} properti ditemukan
          </h2>
        </div>
        {pagination ? (
          <p>
            Halaman {pagination.page} dari {Math.max(pagination.totalPages, 1)}
          </p>
        ) : null}
      </div>
      {content}
    </section>
  );
}

function DetailState({
  detail,
  error,
  loading,
  onBack,
  onToggleWishlist,
  wishlisted,
}: DetailStateProps) {
  if (loading) {
    return (
      <div aria-live="polite" className="status-panel" role="status">
        Memuat detail properti...
      </div>
    );
  }
  if (error) {
    return (
      <div className="status-panel status-panel--error" role="alert">
        <p>{error}</p>
        <button onClick={onBack} type="button">
          Kembali ke hasil
        </button>
      </div>
    );
  }
  return detail ? (
    <PropertyDetail
      onBack={onBack}
      onToggleWishlist={onToggleWishlist}
      property={detail}
      wishlisted={wishlisted}
    />
  ) : null;
}

// apps/airbnb-vue-app/src/components/PropertyExplorer.vue
<script setup lang="ts">
  import type {
    PaginatedResponse,
    PropertyDetail as PropertyDetailType,
    PropertyListItem,
  } from "@airbnb-skripsi/api/catalog";
  import { computed, onMounted, onUnmounted, shallowRef } from "vue";
  import {
    type CatalogFilters,
    type CatalogOptions,
    createCatalogSearchParams,
    createDefaultFilters,
    createPropertyPath,
    fetchCatalogOptions,
    fetchPropertyDetail,
    fetchPropertyPage,
    parseCatalogFilters,
    parsePropertySlug,
  } from "../catalog";
  import PropertyDetail from "./PropertyDetail.vue";
  import PropertyGrid from "./PropertyGrid.vue";
  import SearchFilters from "./SearchFilters.vue";

  type PaginationMeta = PaginatedResponse<PropertyListItem>["meta"];

  const options = shallowRef<CatalogOptions>({
    amenities: [],
    locations: [],
    propertyTypes: [],
  });
  const filters = shallowRef<CatalogFilters>(createDefaultFilters());
  const filterFormKey = shallowRef(0);
  const properties = shallowRef<PropertyListItem[]>([]);
  const pagination = shallowRef<PaginationMeta | null>(null);
  const detail = shallowRef<PropertyDetailType | null>(null);
  const selectedSlug = shallowRef<string | null>(null);
  const wishlistStates = shallowRef<Map<string, boolean>>(new Map());
  const loadingOptions = shallowRef(false);
  const loadingList = shallowRef(false);
  const loadingDetail = shallowRef(false);
  const optionsError = shallowRef<string | null>(null);
  const listError = shallowRef<string | null>(null);
  const detailError = shallowRef<string | null>(null);
  let listRequestId = 0;
  let detailRequestId = 0;

  const errorMessage = computed(() => listError.value ?? optionsError.value);
  const resultLabel = computed(() => {
    const total = pagination.value?.total ?? 0;
    return `${total} properti ditemukan`;
  });

  onMounted(() => {
    window.addEventListener("popstate", handlePopState);
    const slug = parsePropertySlug(window.location.pathname);

    if (slug) {
      openProperty(slug, false);
    } else {
      restoreFiltersFromUrl();
      initialize();
    }
  });

  onUnmounted(() => {
    window.removeEventListener("popstate", handlePopState);
  });

  async function initialize(): Promise<void> {
    await Promise.all([loadOptions(), loadProperties(true)]);
  }

  async function loadOptions(): Promise<void> {
    loadingOptions.value = true;
    optionsError.value = null;

    try {
      options.value = await fetchCatalogOptions();
    } catch (error) {
      optionsError.value = messageFrom(error);
    } finally {
      loadingOptions.value = false;
    }
  }

  async function loadProperties(reset: boolean): Promise<void> {
    const requestId = ++listRequestId;
    const nextPage = reset ? 1 : (pagination.value?.page ?? 0) + 1;
    loadingList.value = true;
    listError.value = null;

    try {
      const response = await fetchPropertyPage(filters.value, nextPage);

      if (requestId !== listRequestId) {
        return;
      }

      properties.value = reset
        ? response.data
        : [...properties.value, ...response.data];
      pagination.value = response.meta;
      mergeWishlist(response.data);
    } catch (error) {
      if (requestId === listRequestId) {
        listError.value = messageFrom(error);
      }
    } finally {
      if (requestId === listRequestId) {
        loadingList.value = false;
      }
    }
  }

  function handleSearch(nextFilters: CatalogFilters): void {
    filters.value = nextFilters;
    updateCatalogUrl(nextFilters);
    clearDetail();
    loadProperties(true);
  }

  function handleReset(): void {
    handleSearch(createDefaultFilters());
  }

  function handlePopState(): void {
    const slug = parsePropertySlug(window.location.pathname);

    if (slug) {
      openProperty(slug, false);
      return;
    }

    restoreFiltersFromUrl();
    clearDetail();
    loadProperties(true);
  }

  function restoreFiltersFromUrl(): void {
    filters.value = parseCatalogFilters(
      new URLSearchParams(window.location.search)
    );
    filterFormKey.value += 1;
  }

  function updateCatalogUrl(nextFilters: CatalogFilters): void {
    const url = new URL(window.location.href);
    url.search = createCatalogSearchParams(
      nextFilters,
      url.searchParams
    ).toString();
    const nextUrl = `${url.pathname}${url.search}${url.hash}`;
    const currentUrl = `${window.location.pathname}${window.location.search}${window.location.hash}`;

    if (nextUrl !== currentUrl) {
      window.history.pushState(null, "", nextUrl);
    }
  }

  async function openProperty(slug: string, updateUrl = true): Promise<void> {
    const requestId = ++detailRequestId;
    selectedSlug.value = slug;
    detail.value = null;
    detailError.value = null;
    loadingDetail.value = true;

    if (updateUrl) {
      const catalogUrl = `${window.location.pathname}${window.location.search}${window.location.hash}`;
      window.history.pushState({ catalogUrl }, "", createPropertyPath(slug));
    }

    window.scrollTo({ behavior: "smooth", top: 0 });

    try {
      const response = await fetchPropertyDetail(slug);

      if (requestId !== detailRequestId) {
        return;
      }

      detail.value = response;
      mergeWishlist([response]);
    } catch (error) {
      if (requestId === detailRequestId) {
        detailError.value = messageFrom(error);
      }
    } finally {
      if (requestId === detailRequestId) {
        loadingDetail.value = false;
      }
    }
  }

  function closeDetail(): void {
    if (typeof window.history.state?.catalogUrl === "string") {
      window.history.back();
      return;
    }

    window.history.pushState(null, "", "/");
    restoreFiltersFromUrl();
    clearDetail();
    initialize();
    window.scrollTo({ behavior: "smooth", top: 0 });
  }

  function clearDetail(): void {
    detailRequestId += 1;
    selectedSlug.value = null;
    detail.value = null;
    detailError.value = null;
    loadingDetail.value = false;
  }

  function toggleWishlist(id: string): void {
    const next = new Map(wishlistStates.value);
    next.set(id, !(next.get(id) ?? false));
    wishlistStates.value = next;
  }

  function mergeWishlist(
    items: Array<PropertyListItem | PropertyDetailType>
  ): void {
    const next = new Map(wishlistStates.value);

    for (const item of items) {
      if (!next.has(item.id)) {
        next.set(item.id, item.isWishlisted);
      }
    }

    wishlistStates.value = next;
  }

  function messageFrom(error: unknown): string {
    return error instanceof Error
      ? error.message
      : "Terjadi kesalahan. Coba lagi.";
  }
</script>

<template>
  <div class="app">
    <a class="skip-link" href="#main-content">Langsung ke konten utama</a>
    <header class="site-header">
      <a class="brand" href="/" aria-label="Airbnb beranda">
        <span class="brand__mark" aria-hidden="true">A</span>
        <span translate="no">Airbnb</span>
      </a>
      <p>
        Prototipe listing
        <span class="site-header__separator" aria-hidden="true">/</span>
        Studi kasus Airbnb
      </p>
    </header>

    <main id="main-content" class="container">
      <template v-if="selectedSlug">
        <div
          v-if="loadingDetail"
          class="status-panel"
          aria-live="polite"
          role="status"
        >
          Memuat detail properti&hellip;
        </div>
        <div
          v-else-if="detailError"
          class="status-panel status-panel--error"
          role="alert"
        >
          <p>{{ detailError }}</p>
          <button type="button" @click="closeDetail">Kembali ke hasil</button>
        </div>
        <PropertyDetail
          v-else-if="detail"
          :property="detail"
          :wishlisted="wishlistStates.get(detail.id) ?? false"
          @back="closeDetail"
          @toggle-wishlist="toggleWishlist"
        />
      </template>

      <template v-else>
        <section class="hero" aria-labelledby="hero-title">
          <div class="hero__intro">
            <div class="hero__copy-block">
              <p class="hero__eyebrow">Eksperimen frontend skripsi</p>
              <h1 id="hero-title">
                Temukan tempat singgah.
                <span>Bandingkan tanpa bias.</span>
              </h1>
              <p class="hero__copy">
                Jelajahi prototipe listing akomodasi dengan pencarian, filter,
                dan detail yang setara pada implementasi Vue dan Svelte.
              </p>
            </div>

            <aside class="research-rail" aria-label="Konteks penelitian">
              <div>
                <span>Dataset</span><strong>Dummy deterministik</strong>
              </div>
              <div><span>API</span><strong>Respons yang sama</strong></div>
              <div><span>Frontend</span><strong>Vue + Svelte</strong></div>
            </aside>
          </div>

          <SearchFilters
            :key="filterFormKey"
            :disabled="loadingList || loadingOptions"
            :initial-filters="filters"
            :options="options"
            @reset="handleReset"
            @search="handleSearch"
          />
        </section>

        <section class="results" aria-labelledby="results-title">
          <div class="results__heading">
            <div>
              <p class="results__eyebrow">Katalog akomodasi</p>
              <h2 id="results-title" aria-live="polite">{{ resultLabel }}</h2>
            </div>
            <p v-if="pagination">
              Halaman {{ pagination.page }} dari
              {{ Math.max(pagination.totalPages, 1) }}
            </p>
          </div>

          <div
            v-if="errorMessage"
            class="status-panel status-panel--error"
            role="alert"
          >
            <p>{{ errorMessage }}</p>
            <button type="button" @click="loadProperties(true)">
              Coba lagi
            </button>
          </div>

          <div
            v-else-if="loadingList && properties.length === 0"
            class="skeleton-grid"
            aria-live="polite"
            role="status"
          >
            <span class="sr-only">Memuat properti&hellip;</span>
            <div v-for="item in 4" :key="item" class="skeleton-card" />
          </div>

          <div
            v-else-if="properties.length === 0"
            class="status-panel"
            aria-live="polite"
          >
            <p>Tidak ada properti yang cocok dengan filter ini.</p>
            <button type="button" @click="handleReset">Reset filter</button>
          </div>

          <template v-else>
            <PropertyGrid
              :properties="properties"
              :wishlist-states="wishlistStates"
              @open="openProperty"
              @toggle-wishlist="toggleWishlist"
            />

            <div class="load-more">
              <button
                v-if="pagination?.hasMore"
                :disabled="loadingList"
                type="button"
                @click="loadProperties(false)"
              >
                {{ loadingList ? "Memuat\u2026" : "Muat lebih banyak" }}
              </button>
              <p v-else>Semua properti sudah ditampilkan.</p>
            </div>
          </template>
        </section>
      </template>
    </main>

    <footer class="site-footer">
      <p><strong>Prototipe akademik</strong></p>
      <p>
        Data dummy deterministik <span aria-hidden="true">&middot;</span>
        Tanpa pemesanan atau transaksi
      </p>
    </footer>
  </div>
</template>
